TODO: in line 112 in xiteclient.py [fix the syncing of blockchain]

TODO: make syncing blockchain when sending a transaction and not mining it, recieve the latest blockchain.

-----------latest------------
after 6/2/24::::
Whats hpappening: Currently when we recieve a transaction from someone who's chain length is greater than ours we send a "SYNC_BC" action
which then is broadcasted to everyone (including us which we have to fix by recieving actions by name or just the "SYNC_BC" with the name), and because of this 
we are saying to ourselfs also that we need our latest blockchain to ourself. but we need to ask the guy who's chain length is longer than use to send his chain.
in the SYNC_BC action we need to send our "latest" blockchain to the guy that asked for it.




march 2024:

the receiver should just do single verify of hash of recieving transaction instead of mining it, if it passes then add to local blockchain, if dont then reject


add initial syncing
if local blockchain isnt latest (lesser blocks than other people) then request random n no. of people, to give their chain length, then compare those chain length to see whose' is
longest then take their chain and download it to our local copy

after 21 april:
the client is now able to determine if its blockchain is latest or not, now use send_whole_blockchain and SEND_BC action to sync the blockchains
- being worked from 21 april 2024










sphinx error april 17 2024:

PS F:\A\xitecoin\docs> .\make.bat html
Running Sphinx v7.3.5
making output directory... done
[autosummary] generating autosummary for: index.rst, modules.rst, xitecoin.rst, xitecoin.util.rst, xitecoin.xite_network.rst, xitecoin.xitelib.rst
WARNING: Failed to import xitecoin.xite_network.xiteclient.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.xiteserver.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.xiteuser.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.util.debug.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.util.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.node.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.sandbox.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.sandbox2.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.sz.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitecoin.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] xitecoin.xitelib
WARNING: autodoc: failed to import module 'sandbox2' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'sz' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitecoin' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'util.debug' from module 'xitecoin'; the following exception was raised:       
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'util' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.util.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.rst
F:\A\xitecoin\docs\xitecoin.util.rst:16: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.rst
WARNING: autodoc: failed to import module 'xite_network.xiteclient' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network.xiteserver' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network.xiteuser' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network' from module 'xitecoin'; the following exception was raised:     
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.xite_network.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.util.rst
F:\A\xitecoin\docs\xitecoin.xite_network.rst:32: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.util.rst
WARNING: autodoc: failed to import module 'xitelib.node' from module 'xitecoin'; the following exception was raised:     
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitelib.sandbox' from module 'xitecoin'; the following exception was raised:  
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitelib' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.xitelib.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.xite_network.rst
F:\A\xitecoin\docs\xitecoin.xitelib.rst:24: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.xite_network.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... F:\A\xitecoin\docs\modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] xitecoin.xitelib
generating indices... genindex done
highlighting module code... 
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 33 warnings.

The HTML pages are in _build\html.