from 22 april:
the blockchains are syncing (but not correctly) some transactions are getting cut if not timed correctly with the check_bc_len() function 
its computing prev_hash after we get the largest bc, but we want to see if what prev_hash we are getting actually matches the prev_has of the previous block by PoW_singlePass function,  apply the verify function before making the prev_hash ourselfs!! 
STOP COMPUTING PREV_HASH OURSELFS!!! THIS SLOWWS DOWN BLOCKCHAIN DOWNLOADING AND CAUSES MORE RESOURCES!



Actual money logic:
make a limited amount of coins, if we exchange real money with those coins, they will still be limited, and if we mine then it will be mined from the total amount of coins.
ppl who mine will get some percentage of the transaction (transaction fees)

solving this:
error in line 195 in xiteclient with this code:if XiteUser.process_mined_block(data, client_user, use_multithreading=False):

inside XiteUser.process_mined_block()  :-
we are making a new default argument named 'reward' which is being added in nwtransaction and transcation method, which is now causing new errors while mining, fix it 


22 APRIL 2024:

TODO 22 april 2024:
1. make a way to sync the blockchain without seeing the largest chain, will be used for errors in local blockchain if we need to sync it. 
2. before making a new transaction make sure that the latest block in local blockchain, if its data's hash is the same as the hash written in the block.

Questions to ask chatgpt:
1. if we mine a block, so is the reward given to the user by the server? if yes then is it its own transaction?, is it its own block?, how do we let people know that i got the reward after mining


24 april 2024:
getting this error with reward mining currently as its giving error that Abhinav1 doesnt have the reward amount to even give so thats y giving error:
Insufficient balance
Error occurred while handling json: Insufficient balance for Abhinav1
TRACEBACK OF CL_HANDLE_JSON:
Traceback (most recent call last):
  File "F:\A\xitecoin\xite_network\xiteclient.py", line 181, in cl_handle_json
    reward_data = client_user.nwtransaction(client_user, REWARD, save = False, return_as_json = True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 70, in nwtransaction
    return super().transaction(recipient, amount, save, return_block=return_as_json, return_data=return_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\xitelib\node.py", line 406, in transaction
    raise InvalidTransactionException(f"Insufficient balance for {self.name}")
xitelib.node.InvalidTransactionException: Insufficient balance for Abhinav1
{
    "action": "BC_TRANSACTION_DATA",
    "sender": "Abhinav2",
    "data": {
        "prev_hash": "",
        "hash": "d60d2b96a8f96edbb6bb13c1a1e1a81639b5f6568ebe1bec6e6364a990a63ca0",
        "data": {
            "sender_name": "Abhinav2",
            "recipient_name": "dfgfdg",
            "amount": 0,
            "message": "Abhinav2 gave dfgfdg 0 $XITE",
            "chain_length": 47
        },
        "timestamp": "23/04/2024 20:52:07",
        "nonce": 0
    },
    "bc_name": "xc_Abhinav2",
    "prev_hash": "33a4eb76160c1fb3ed6a1bd2e9ab38859efb7bcd36d887a93530b0bddddb3d2e"
}


After 21 may 2024:
1. fix the block.prev_hash not being set so it is not used to find the new hash, first make sure if this is the case or not, it could be that it IS having .prev_hash value and making the hash the same cuz the previous blocks are the exact same (could really well be the case) or that its makign the same hash again and again cuz its not having prev_hash.

2. sometimes a client doesnt receieve the transaction for whatever reason and thats why the blockchains go out of sync, i have commented the check_bc_len function so for now its not syncing bc when its recieving transactions, its only checking and syncing when its itself doing a transaction (above the make_transaction function in the write function), fix all of this

















sphinx error april 17 2024:

PS F:\A\xitecoin\docs> .\make.bat html
Running Sphinx v7.3.5
making output directory... done
[autosummary] generating autosummary for: index.rst, modules.rst, xitecoin.rst, xitecoin.util.rst, xitecoin.xite_network.rst, xitecoin.xitelib.rst
WARNING: Failed to import xitecoin.xite_network.xiteclient.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.xiteserver.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.xiteuser.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xite_network.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.util.debug.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.util.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.node.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.sandbox.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitelib.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.sandbox2.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.sz.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.xitecoin.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
WARNING: Failed to import xitecoin.
Possible hints:
* KeyError: 'xitecoin'
* FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'
The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] xitecoin.xitelib
WARNING: autodoc: failed to import module 'sandbox2' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'sz' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitecoin' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'util.debug' from module 'xitecoin'; the following exception was raised:       
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'util' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.util.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.rst
F:\A\xitecoin\docs\xitecoin.util.rst:16: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.rst
WARNING: autodoc: failed to import module 'xite_network.xiteclient' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network.xiteserver' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network.xiteuser' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xite_network' from module 'xitecoin'; the following exception was raised:     
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.xite_network.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.util.rst
F:\A\xitecoin\docs\xitecoin.xite_network.rst:32: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.util.rst
WARNING: autodoc: failed to import module 'xitelib.node' from module 'xitecoin'; the following exception was raised:     
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitelib.sandbox' from module 'xitecoin'; the following exception was raised:  
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

WARNING: autodoc: failed to import module 'xitelib' from module 'xitecoin'; the following exception was raised:
Traceback (most recent call last):
  File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\sphinx\ext\autodoc\importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\A\xitecoin\xitecoin.py", line 1, in <module>
    from xite_network.xiteuser import XiteUser
  File "F:\A\xitecoin\xite_network\xiteuser.py", line 1, in <module>
    from xitelib.node import Blockchain, Data, User, Block
  File "F:\A\xitecoin\xitelib\node.py", line 26, in <module>
    from settings.settings import Settings
  File "F:\A\xitecoin\settings\settings.py", line 17, in <module>
    settings = import_xml_settings('settings/blockchain_settings.xml')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\A\xitecoin\settings\settings.py", line 5, in import_xml_settings
    tree = ET.parse(file_path)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse        
    tree.parse(source, parser)
  File "C:\Users\abhin\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings/blockchain_settings.xml'

F:\A\xitecoin\docs\xitecoin.xitelib.rst:5: WARNING: duplicate label submodules, other instance in F:\A\xitecoin\docs\xitecoin.xite_network.rst
F:\A\xitecoin\docs\xitecoin.xitelib.rst:24: WARNING: duplicate label module contents, other instance in F:\A\xitecoin\docs\xitecoin.xite_network.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... F:\A\xitecoin\docs\modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] xitecoin.xitelib
generating indices... genindex done
highlighting module code... 
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 33 warnings.

The HTML pages are in _build\html.